apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-scripts
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservices-app.customLabels" . | nindent 4 }}
    app.kubernetes.io/component: database-init
data:
  resources-init.sql: |
    CREATE SEQUENCE IF NOT EXISTS public.resources_id_seq
        INCREMENT BY 1
        MINVALUE 1
        MAXVALUE 2147483647
        START 1
        CACHE 1
        NO CYCLE;
    
    CREATE TABLE IF NOT EXISTS public.resources (
        id int4 NOT NULL DEFAULT nextval('resources_id_seq'),
        blob bytea NULL,
        CONSTRAINT resources_pkey PRIMARY KEY (id)
        );

  songs-init.sql: |
    CREATE TABLE IF NOT EXISTS public.songs (
        id int4 NOT NULL,
        resource_id int4 NOT NULL,
        album varchar(255) NULL,
        artist varchar(255) NULL,
        length varchar(255) NULL,
        name varchar(255) NULL,
        year varchar(255) NULL,
        genre varchar(255) NULL,
        CONSTRAINT songs_pkey PRIMARY KEY (id),
        CONSTRAINT songs_resource_id_key UNIQUE (resource_id)
        );

