apiVersion: v1
kind: Service
metadata:
  name: resource-svc
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: resource-pod
  ports:
    - protocol: TCP
      port: {{ .Values.resourceService.port }}
      targetPort: {{ .Values.resourceService.port }}
      nodePort: {{ .Values.resourceService.nodePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: song-svc
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: song-pod
  ports:
    - protocol: TCP
      port: {{ .Values.songService.port }}
      targetPort: {{ .Values.songService.port }}
      nodePort: {{ .Values.songService.nodePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: songs-db
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: songs-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: resources-db
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: resources-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.eurekaService.eurekaServiceName }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: eureka-pod
  ports:
    - protocol: TCP
      port: {{ .Values.eurekaService.port }}
      targetPort: {{ .Values.eurekaService.port }}
      nodePort: {{ .Values.eurekaService.nodePort }}

