# resource-service VERSION 2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-deployment
  namespace: k8s-program
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: resource-pod
  template:
    metadata:
      labels:
        app: resource-pod
        version: "2"
    spec:
      containers:
        - name: resource-service
          image: resource-service:2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: RESOURCES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: RESOURCES_DB_HOST
            - name: RESOURCES_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: RESOURCES_DB_PORT
            - name: RESOURCES_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: RESOURCES_DB_NAME
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SONGS_MS_URL
              value: "song-svc"
            - name: SONGS_MS_PORT
              value: "8080"
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
# song-service VERSION 2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-deployment
  namespace: k8s-program
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: song-pod
  template:
    metadata:
      labels:
        app: song-pod
        version: "2"
    spec:
      containers:
        - name: song-service
          image: song-service:2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SONGS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: SONGS_DB_HOST
            - name: SONGS_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: SONGS_DB_PORT
            - name: SONGS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: SONGS_DB_NAME
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: song-storage
              mountPath: /app/data
      volumes:
        - name: song-storage
          persistentVolumeClaim:
            claimName: song-pvc
