# Secret для учетных данных PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: k8s-program
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
